//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCharge.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartCharge.Application.ExceptionsMessages", typeof(ExceptionsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity In Amps should be greater than zero..
        /// </summary>
        public static string CapacityInAmpsGreaterThanZero {
            get {
                return ResourceManager.GetString("CapacityInAmpsGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected Id should be between 0 and 5..
        /// </summary>
        public static string ConnectorIdOutOfRange {
            get {
                return ResourceManager.GetString("ConnectorIdOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group CapacityInAmps  shoul be greater than MaxCurrentAmps of connectors.
        /// </summary>
        public static string InvalidGroupCapacityInAmps {
            get {
                return ResourceManager.GetString("InvalidGroupCapacityInAmps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each Charge Station can not have more than five connectors..
        /// </summary>
        public static string MaxConnectorsCount {
            get {
                return ResourceManager.GetString("MaxConnectorsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Current In Amps should be greater than zero..
        /// </summary>
        public static string MaxCurrentInAmpsGreaterThanZero {
            get {
                return ResourceManager.GetString("MaxCurrentInAmpsGreaterThanZero", resourceCulture);
            }
        }
    }
}
